-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Gazdă: 127.0.0.1
-- Timp de generare: mart. 09, 2020 la 07:52 PM
-- Versiune server: 10.1.38-MariaDB
-- Versiune PHP: 7.3.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Bază de date: `movies`
--

-- --------------------------------------------------------

--
-- Structură tabel pentru tabel `movies`
--

CREATE TABLE `movies` (
  `id` int(11) NOT NULL,
  `title` text COLLATE utf8_unicode_ci NOT NULL,
  `year` text COLLATE utf8_unicode_ci NOT NULL,
  `runtime` text COLLATE utf8_unicode_ci NOT NULL,
  `genre` text COLLATE utf8_unicode_ci NOT NULL,
  `director` text COLLATE utf8_unicode_ci NOT NULL,
  `actors` text COLLATE utf8_unicode_ci NOT NULL,
  `language` text COLLATE utf8_unicode_ci NOT NULL,
  `awards` text COLLATE utf8_unicode_ci NOT NULL,
  `imdb_rating` text COLLATE utf8_unicode_ci NOT NULL,
  `poster` text COLLATE utf8_unicode_ci NOT NULL,
  `plot` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Eliminarea datelor din tabel `movies`
--

INSERT INTO `movies` (`id`, `title`, `year`, `runtime`, `genre`, `director`, `actors`, `language`, `awards`, `imdb_rating`, `poster`, `plot`) VALUES
(1, 'The Shawshank Redemption', '1994', '142 min', 'Drama', 'Frank Darabont', 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler', 'English', 'Nominated for 7 Oscars. Another 21 wins & 35 nominations.', '9.3', 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.'),
(2, 'The Godfather', '1972', '175 min', 'Crime, Drama', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano', 'English, Italian, Latin', 'Won 3 Oscars. Another 26 wins & 30 nominations.', '9.2', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.'),
(3, 'The Godfather: Part II', '1974', '202 min', 'Crime, Drama', 'Francis Ford Coppola', 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro', 'English, Italian, Spanish, Latin, Sicilian', 'Won 6 Oscars. Another 11 wins & 20 nominations.', '9.0', 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.'),
(4, 'The Dark Knight', '2008', '152 min', 'Action, Crime, Drama, Thriller', 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine', 'English, Mandarin', 'Won 2 Oscars. Another 153 wins & 159 nominations.', '9.0', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.'),
(5, '12 Angry Men', '1957', '96 min', 'Drama', 'Sidney Lumet', 'Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall', 'English', 'Nominated for 3 Oscars. Another 16 wins & 9 nominations.', '8.9', 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.'),
(6, 'Schindler\'s List', '1993', '195 min', 'Biography, Drama, History', 'Steven Spielberg', 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall', 'English, Hebrew, German, Polish', 'Won 7 Oscars. Another 83 wins & 49 nominations.', '8.9', 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.'),
(7, 'The Lord of the Rings: The Return of the King', '2003', '201 min', 'Adventure, Drama, Fantasy', 'Peter Jackson', 'Noel Appleby, Ali Astin, Sean Astin, David Aston', 'English, Quenya, Old English, Sindarin', 'Won 11 Oscars. Another 199 wins & 122 nominations.', '8.9', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.'),
(8, 'Pulp Fiction', '1994', '154 min', 'Crime, Drama', 'Quentin Tarantino', 'Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta', 'English, Spanish, French', 'Won 1 Oscar. Another 68 wins & 74 nominations.', '8.9', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.'),
(9, 'The Lord of the Rings: The Fellowship of the Ring', '2001', '178 min', 'Adventure, Drama, Fantasy', 'Peter Jackson', 'Alan Howard, Noel Appleby, Sean Astin, Sala Baker', 'English, Sindarin', 'Won 4 Oscars. Another 115 wins & 124 nominations.', '8.8', 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.'),
(10, 'Fight Club', '1999', '139 min', 'Drama', 'David Fincher', 'Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier', 'English', 'Nominated for 1 Oscar. Another 10 wins & 37 nominations.', '8.8', 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.'),
(11, 'Forrest Gump', '1994', '142 min', 'Drama, Romance', 'Robert Zemeckis', 'Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys', 'English', 'Won 6 Oscars. Another 44 wins & 74 nominations.', '8.8', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.'),
(12, 'Inception', '2010', '148 min', 'Action, Adventure, Sci-Fi, Thriller', 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy', 'English, Japanese, French', 'Won 4 Oscars. Another 152 wins & 210 nominations.', '8.8', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.'),
(13, 'Star Wars: Episode V - The Empire Strikes Back', '1980', '124 min', 'Action, Adventure, Fantasy, Sci-Fi', 'Irvin Kershner', 'Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams', 'English', 'Won 1 Oscar. Another 24 wins & 19 nominations.', '8.7', 'https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy.'),
(14, 'The Lord of the Rings: The Two Towers', '2002', '179 min', 'Adventure, Drama, Fantasy', 'Peter Jackson', 'Bruce Allpress, Sean Astin, John Bach, Sala Baker', 'English, Sindarin, Old English', 'Won 2 Oscars. Another 123 wins & 137 nominations.', '8.7', 'https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.'),
(15, 'The Matrix', '1999', '136 min', 'Action, Sci-Fi', 'Lana Wachowski, Lilly Wachowski', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving', 'English', 'Won 4 Oscars. Another 37 wins & 50 nominations.', '8.7', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.'),
(16, 'Goodfellas', '1990', '146 min', 'Biography, Crime, Drama', 'Martin Scorsese', 'Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco', 'English, Italian', 'Won 1 Oscar. Another 43 wins & 38 nominations.', '8.7', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.'),
(17, 'One Flew Over the Cuckoo\'s Nest', '1975', '133 min', 'Drama', 'Milos Forman', 'Jack Nicholson, Louise Fletcher, Will Sampson, Michael Berryman', 'English', 'Won 5 Oscars. Another 30 wins & 13 nominations.', '8.7', 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.'),
(18, 'Se7en', '1995', '127 min', 'Crime, Drama, Mystery, Thriller', 'David Fincher', 'Morgan Freeman, Andrew Kevin Walker, Daniel Zacapa, Brad Pitt', 'English', 'Nominated for 1 Oscar. Another 26 wins & 40 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.'),
(19, 'The Silence of the Lambs', '1991', '118 min', 'Crime, Drama, Thriller', 'Jonathan Demme', 'Jodie Foster, Lawrence A. Bonney, Kasi Lemmons, Lawrence T. Wrentz', 'English, Latin', 'Won 5 Oscars. Another 63 wins & 51 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.'),
(20, 'It\'s a Wonderful Life', '1946', '130 min', 'Drama, Family, Fantasy', 'Frank Capra', 'James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell', 'English, French', 'Nominated for 5 Oscars. Another 6 wins & 1 nomination.', '8.6', 'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg', 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.'),
(21, 'Star Wars: Episode IV - A New Hope', '1977', '121 min', 'Action, Adventure, Fantasy, Sci-Fi', 'George Lucas', 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing', 'English', 'Won 6 Oscars. Another 52 wins & 28 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire\'s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.'),
(22, 'Saving Private Ryan', '1998', '169 min', 'Drama, War', 'Steven Spielberg', 'Tom Hanks, Tom Sizemore, Edward Burns, Barry Pepper', 'English, French, German, Czech', 'Won 5 Oscars. Another 74 wins & 74 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.'),
(23, 'The Green Mile', '1999', '189 min', 'Crime, Drama, Fantasy, Mystery', 'Frank Darabont', 'Tom Hanks, David Morse, Bonnie Hunt, Michael Clarke Duncan', 'English, French', 'Nominated for 4 Oscars. Another 15 wins & 33 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.'),
(24, 'Interstellar', '2014', '169 min', 'Adventure, Drama, Sci-Fi', 'Christopher Nolan', 'Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow', 'English', 'Won 1 Oscar. Another 43 wins & 145 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.'),
(25, 'L.A. on $5 a Day', '1989', 'N/A', 'N/A', 'Todd Hughes', 'Dan Teachout, Mary Scheer, Lisa Kudrow, Shawm Brydon', 'N/A', 'N/A', '7.8', 'N/A', 'N/A'),
(26, 'The Usual Suspects', '1995', '106 min', 'Crime, Mystery, Thriller', 'Bryan Singer', 'Stephen Baldwin, Gabriel Byrne, Benicio Del Toro, Kevin Pollak', 'English, Hungarian, Spanish, French', 'Won 2 Oscars. Another 35 wins & 16 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'),
(27, 'Seppuku', '2016', 'N/A', 'Short, Drama', 'Daryn Wakasa', 'Tamlyn Tomita, Yuji Okumoto, Akemi Look, Jenny Greer', 'English', 'N/A', 'N/A', 'N/A', 'N/A'),
(28, 'The Lion King', '1994', '88 min', 'Animation, Adventure, Drama, Family, Musical', 'Roger Allers, Rob Minkoff', 'Rowan Atkinson, Matthew Broderick, Niketa Calame-Harris, Jim Cummings', 'English, Swahili, Xhosa, Zulu', 'Won 2 Oscars. Another 35 wins & 34 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg', 'A Lion cub crown prince is tricked by a treacherous uncle into thinking he caused his father\'s death and flees into exile in despair, only to learn in adulthood his identity and his responsibilities.'),
(29, 'American History X', '1998', '119 min', 'Drama', 'Tony Kaye', 'Edward Norton, Edward Furlong, Beverly D\'Angelo, Jennifer Lien', 'English', 'Nominated for 1 Oscar. Another 4 wins & 13 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BZjA0MTM4MTQtNzY5MC00NzY3LWI1ZTgtYzcxMjkyMzU4MDZiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.'),
(30, 'Terminator 2: Judgment Day', '1991', '137 min', 'Action, Sci-Fi', 'James Cameron', 'Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick', 'English, Spanish', 'Won 4 Oscars. Another 32 wins & 33 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.'),
(31, 'The Pianist', '2002', '150 min', 'Biography, Drama, Music, War', 'Roman Polanski', 'Adrien Brody, Emilia Fox, Michal Zebrowski, Ed Stoppard', 'English, German, Russian', 'Won 3 Oscars. Another 54 wins & 73 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.'),
(32, 'Back to the Future', '1985', '116 min', 'Adventure, Comedy, Sci-Fi', 'Robert Zemeckis', 'Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover', 'English', 'Won 1 Oscar. Another 19 wins & 25 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.'),
(33, 'Modern Times', '1936', '87 min', 'Comedy, Drama, Family, Romance', 'Charles Chaplin', 'Charles Chaplin, Paulette Goddard, Henry Bergman, Tiny Sandford', 'English', '4 wins & 1 nomination.', '8.5', 'https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.'),
(34, 'Psycho', '1960', '109 min', 'Horror, Mystery, Thriller', 'Alfred Hitchcock', 'Anthony Perkins, Vera Miles, John Gavin, Janet Leigh', 'English', 'Nominated for 4 Oscars. Another 5 wins & 10 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'A Phoenix secretary embezzles forty thousand dollars from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.'),
(35, 'Gladiator', '2000', '155 min', 'Action, Adventure, Drama', 'Ridley Scott', 'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed', 'English', 'Won 5 Oscars. Another 54 wins & 104 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.'),
(36, 'City Lights', '1931', '87 min', 'Comedy, Drama, Romance', 'Charles Chaplin', 'Virginia Cherrill, Florence Lee, Harry Myers, Al Ernest Garcia', 'English', '3 wins.', '8.5', 'https://m.media-amazon.com/images/M/MV5BY2I4MmM1N2EtM2YzOS00OWUzLTkzYzctNDc5NDg2N2IyODJmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.'),
(37, 'Intouchables', '2016', '19 min', 'Short, Drama', 'Junyi Shen', 'N/A', 'Chinese', 'N/A', '8.1', 'N/A', 'Meng Xia\'s son is lost. He is among the tens of thousands, mostly boys, who are kidnapped and sold in China.'),
(38, 'The Departed', '2006', '151 min', 'Crime, Drama, Thriller', 'Martin Scorsese', 'Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg', 'English, Cantonese', 'Won 4 Oscars. Another 94 wins & 139 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.'),
(39, 'Whiplash', '2014', '106 min', 'Drama, Music', 'Damien Chazelle', 'Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist', 'English', 'Won 3 Oscars. Another 90 wins & 140 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.'),
(40, 'Joker', '2019', '122 min', 'Crime, Drama, Thriller', 'Todd Phillips', 'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy', 'English', 'Won 2 Oscars. Another 57 wins & 163 nominations.', '8.6', 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.'),
(41, 'The Prestige', '2006', '130 min', 'Drama, Mystery, Sci-Fi, Thriller', 'Christopher Nolan', 'Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo', 'English', 'Nominated for 2 Oscars. Another 6 wins & 38 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.'),
(42, 'Casablanca', '1942', '102 min', 'Drama, Romance, War', 'Michael Curtiz', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains', 'English, French, German, Italian', 'Won 3 Oscars. Another 5 wins & 9 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg', 'A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.'),
(43, 'Rear Window', '1954', '112 min', 'Mystery, Thriller', 'Alfred Hitchcock', 'James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter', 'English', 'Nominated for 4 Oscars. Another 6 wins & 9 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.'),
(44, 'Alien', '1979', '117 min', 'Horror, Sci-Fi', 'Ridley Scott', 'Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton', 'English', 'Won 1 Oscar. Another 16 wins & 20 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMmQ2MmU3NzktZjAxOC00ZDZhLTk4YzEtMDMyMzcxY2IwMDAyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun.'),
(45, 'Apocalypse Now', '1979', '147 min', 'Drama, Mystery, War', 'Francis Ford Coppola', 'Marlon Brando, Martin Sheen, Robert Duvall, Frederic Forrest', 'English, French, Vietnamese', 'Won 2 Oscars. Another 18 wins & 31 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMDdhODg0MjYtYzBiOS00ZmI5LWEwZGYtZDEyNDU4MmQyNzFkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.'),
(46, 'Raiders of the Lost Ark', '1981', '115 min', 'Action, Adventure', 'Steven Spielberg', 'Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey', 'English, German, Hebrew, Spanish, Arabic, Nepali', 'Won 4 Oscars. Another 31 wins & 24 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_SX300.jpg', 'In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler\'s Nazis can obtain its awesome powers.'),
(47, 'Memento', '2000', '113 min', 'Mystery, Thriller', 'Christopher Nolan', 'Guy Pearce, Carrie-Anne Moss, Joe Pantoliano, Mark Boone Junior', 'English', 'Nominated for 2 Oscars. Another 57 wins & 56 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A man with short-term memory loss attempts to track down his wife\'s murderer.'),
(48, 'The Great Dictator', '1940', '125 min', 'Comedy, Drama, War', 'Charles Chaplin', 'Charles Chaplin, Jack Oakie, Reginald Gardiner, Henry Daniell', 'English, Esperanto', 'Nominated for 5 Oscars. Another 6 wins & 1 nomination.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel\'s regime.'),
(49, 'Django Unchained', '2012', '165 min', 'Drama, Western', 'Quentin Tarantino', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington', 'English, German, French, Italian', 'Won 2 Oscars. Another 57 wins & 153 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.'),
(50, '1917', '2019', '119 min', 'Drama, War', 'Sam Mendes', 'Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth', 'English, French, German', 'Won 3 Oscars. Another 103 wins & 152 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg', 'April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.'),
(51, 'Avengers: Infinity War', '2018', '149 min', 'Action, Adventure, Sci-Fi', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans', 'English', 'Nominated for 1 Oscar. Another 44 wins & 70 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg', 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(52, 'Paths of Glory', '1957', '88 min', 'Drama, War', 'Stanley Kubrick', 'Kirk Douglas, Ralph Meeker, Adolphe Menjou, George Macready', 'English, German, Latin', 'Nominated for 1 BAFTA Film Award. Another 5 wins & 2 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BNjViMmRkOTEtM2ViOS00ODg0LWJhYWEtNTBlOGQxNDczOGY3XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg', 'After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.'),
(53, 'The Shining', '1980', '146 min', 'Drama, Horror', 'Stanley Kubrick', 'Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers', 'English', '4 wins & 7 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.'),
(54, 'Spider-Man: Into the Spider-Verse', '2018', '117 min', 'Animation, Action, Adventure, Family, Sci-Fi', 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 'Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali', 'English, Spanish', 'Won 1 Oscar. Another 75 wins & 53 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg', 'Teen Miles Morales becomes Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat for all realities.'),
(55, 'Sunset Blvd.', '1950', '110 min', 'Drama, Film-Noir', 'Billy Wilder', 'William Holden, Gloria Swanson, Erich von Stroheim, Nancy Olson', 'English', 'Won 3 Oscars. Another 15 wins & 19 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMTU0NTkyNzYwMF5BMl5BanBnXkFtZTgwMDU0NDk5MTI@._V1_SX300.jpg', 'A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.'),
(56, 'Avengers: Endgame', '2019', '181 min', 'Action, Adventure, Drama, Sci-Fi', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth', 'English, Japanese, Xhosa, German', 'Nominated for 1 Oscar. Another 46 wins & 97 nominations.', '8.5', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg', 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.'),
(57, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', '1964', '95 min', 'Comedy', 'Stanley Kubrick', 'Peter Sellers, George C. Scott, Sterling Hayden, Keenan Wynn', 'English, Russian', 'Nominated for 4 Oscars. Another 13 wins & 7 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'An insane general triggers a path to nuclear holocaust that a War Room full of politicians and generals frantically tries to stop.'),
(58, 'Witness for the Prosecution', '1957', '116 min', 'Crime, Drama, Film-Noir, Mystery, Thriller', 'Billy Wilder', 'Tyrone Power, Marlene Dietrich, Charles Laughton, Elsa Lanchester', 'English, German', 'Nominated for 6 Oscars. Another 3 wins & 9 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BZjEwMmE5MzYtYWExYy00ZjEzLTk4MjUtMmJmNzgxY2MxN2U1XkEyXkFqcGdeQXVyMTg2NTc4MzA@._V1_SX300.jpg', 'A veteran British barrister must defend his client in a murder trial that has surprise after surprise.'),
(59, 'The Dark Knight Rises', '2012', '164 min', 'Action, Adventure, Thriller', 'Christopher Nolan', 'Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt', 'English, Arabic', 'Nominated for 1 BAFTA Film Award. Another 38 wins & 101 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg', 'Eight years after the Joker\'s reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.'),
(60, 'Once Upon a Time in America', '1984', '229 min', 'Crime, Drama', 'Sergio Leone', 'Robert De Niro, James Woods, Elizabeth McGovern, Treat Williams', 'English, Italian, French', 'Nominated for 2 Golden Globes. Another 11 wins & 8 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.'),
(61, 'Aliens', '1986', '137 min', 'Action, Adventure, Sci-Fi, Thriller', 'James Cameron', 'Sigourney Weaver, Carrie Henn, Michael Biehn, Paul Reiser', 'English', 'Won 2 Oscars. Another 18 wins & 23 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Ellen Ripley is rescued by a deep salvage team after being in hypersleep for 57 years. The moon that the Nostromo visited has been colonized, but contact is lost. This time, colonial marines have impressive firepower, but will that be enough?'),
(62, 'Kimi no na wa: Dai-ni-bu', '1953', '120 min', 'Drama, Romance', 'Hideo Ôba', 'Keiko Awaji, Chikage Awashima, Kimie Hayashi, Shin\'ichi Himori', 'Japanese', 'N/A', '6.2', 'N/A', 'N/A'),
(63, 'American Beauty', '1999', '122 min', 'Drama', 'Sam Mendes', 'Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley', 'English', 'Won 5 Oscars. Another 106 wins & 101 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter\'s best friend.'),
(64, 'Coco', '2017', '105 min', 'Animation, Adventure, Family, Fantasy, Music, Mystery', 'Lee Unkrich, Adrian Molina(co-director)', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach', 'English, Spanish', 'Won 2 Oscars. Another 108 wins & 35 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg', 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.'),
(65, 'Braveheart', '1995', '178 min', 'Biography, Drama, History, War', 'Mel Gibson', 'James Robinson, Sean Lawlor, Sandy Nelson, James Cosmo', 'English, French, Latin, Scottish Gaelic, Italian', 'Won 5 Oscars. Another 28 wins & 32 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt against King Edward I of England.'),
(66, '3 Idiots', '2009', '170 min', 'Comedy, Drama', 'Rajkumar Hirani', 'Aamir Khan, Madhavan, Sharman Joshi, Kareena Kapoor', 'Hindi, English', '62 wins & 23 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them \"idiots\".'),
(67, 'Toy Story', '1995', '81 min', 'Animation, Adventure, Comedy, Family, Fantasy', 'John Lasseter', 'Tom Hanks, Tim Allen, Don Rickles, Jim Varney', 'English', 'Nominated for 3 Oscars. Another 27 wins & 20 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy\'s room.'),
(68, 'Tengoku to jigoku', '2007', 'N/A', 'Drama, Thriller', 'Yasuo Tsuruhashi', 'Hiroshi Abe, Shima Ohnishi, Kôichi Satô, Kyôka Suzuki', 'Japanese', 'N/A', '5.3', 'N/A', 'N/A'),
(69, 'Star Wars: Episode VI - Return of the Jedi', '1983', '131 min', 'Action, Adventure, Fantasy, Sci-Fi', 'Richard Marquand', 'Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams', 'English', 'Nominated for 4 Oscars. Another 22 wins & 16 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BOWZlMjFiYzgtMTUzNC00Y2IzLTk1NTMtZmNhMTczNTk0ODk1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg', 'After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor\'s trap.'),
(70, 'Amadeus', '1984', '160 min', 'Biography, Drama, History, Music', 'Milos Forman', 'F. Murray Abraham, Tom Hulce, Elizabeth Berridge, Roy Dotrice', 'English, Italian, Latin, German', 'Won 8 Oscars. Another 34 wins & 14 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg', 'The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was insanely jealous of Mozart\'s talent and claimed to have murdered him.'),
(71, 'Reservoir Dogs', '1992', '99 min', 'Crime, Drama, Thriller', 'Quentin Tarantino', 'Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn', 'English', '12 wins & 22 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.'),
(72, 'Inglourious Basterds', '2009', '153 min', 'Adventure, Drama, War', 'Quentin Tarantino', 'Brad Pitt, Mélanie Laurent, Christoph Waltz, Eli Roth', 'English, German, French, Italian', 'Won 1 Oscar. Another 132 wins & 171 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.'),
(73, 'Good Will Hunting', '1997', '126 min', 'Drama, Romance', 'Gus Van Sant', 'Matt Damon, Ben Affleck, Stellan Skarsgård, John Mighton', 'English', 'Won 2 Oscars. Another 22 wins & 60 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', 'Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.'),
(74, '2001: A Space Odyssey', '1968', '149 min', 'Adventure, Sci-Fi', 'Stanley Kubrick', 'Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter', 'English, Russian', 'Won 1 Oscar. Another 15 wins & 10 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins with help from intelligent supercomputer H.A.L. 9000.'),
(75, 'Requiem for a Dream', '2000', '102 min', 'Drama', 'Darren Aronofsky', 'Ellen Burstyn, Jared Leto, Jennifer Connelly, Marlon Wayans', 'English', 'Nominated for 1 Oscar. Another 34 wins & 63 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.'),
(76, 'Vertigo', '1958', '128 min', 'Mystery, Romance, Thriller', 'Alfred Hitchcock', 'James Stewart, Kim Novak, Barbara Bel Geddes, Tom Helmore', 'English', 'Nominated for 2 Oscars. Another 8 wins & 5 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BYTE4ODEwZDUtNDFjOC00NjAxLWEzYTQtYTI1NGVmZmFlNjdiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'A former police detective juggles wrestling with his personal demons and becoming obsessed with a hauntingly beautiful woman.'),
(77, 'Dangal', '2016', '161 min', 'Action, Biography, Drama, Sport', 'Nitesh Tiwari', 'Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Sakshi Tanwar', 'Hindi, Tamil, Telugu', '23 wins & 6 nominations.', '8.4', 'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SX300.jpg', 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.'),
(78, 'Eternal Sunshine of the Spotless Mind', '2004', '108 min', 'Drama, Romance, Sci-Fi', 'Michel Gondry', 'Jim Carrey, Kate Winslet, Gerry Robert Byrne, Elijah Wood', 'English', 'Won 1 Oscar. Another 72 wins & 110 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg', 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.'),
(79, 'Citizen Kane', '1941', '119 min', 'Drama, Mystery', 'Orson Welles', 'Joseph Cotten, Dorothy Comingore, Agnes Moorehead, Ruth Warrick', 'English, Italian', 'Won 1 Oscar. Another 9 wins & 13 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance; \'Rosebud\'.'),
(80, 'Robin Hat & Jagten på den forsvundne hat', '1985–', '15 min', 'N/A', 'N/A', 'Michael Wikke, Steen Rasmussen, Hans Henrik Bærentsen', 'Danish', 'N/A', '7.2', 'N/A', 'N/A'),
(81, 'Full Metal Jacket', '1987', '116 min', 'Drama, War', 'Stanley Kubrick', 'Matthew Modine, Adam Baldwin, Vincent D\'Onofrio, R. Lee Ermey', 'English, Vietnamese', 'Nominated for 1 Oscar. Another 8 wins & 13 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNzkxODk0NjEtYjc4Mi00ZDI0LTgyYjEtYzc1NDkxY2YzYTgyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.'),
(82, 'North by Northwest', '1959', '136 min', 'Adventure, Mystery, Thriller', 'Alfred Hitchcock', 'Cary Grant, Eva Marie Saint, James Mason, Jessie Royce Landis', 'English, French', 'Nominated for 3 Oscars. Another 8 wins & 7 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies.'),
(83, 'A Clockwork Orange', '1971', '136 min', 'Crime, Drama, Sci-Fi', 'Stanley Kubrick', 'Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke', 'English', 'Nominated for 4 Oscars. Another 9 wins & 19 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg', 'In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn\'t go as planned.'),
(84, 'Snatch', '2000', '102 min', 'Comedy, Crime', 'Guy Ritchie', 'Benicio Del Toro, Dennis Farina, Vinnie Jones, Brad Pitt', 'English, Russian', '4 wins & 6 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMTA2NDYxOGYtYjU1Mi00Y2QzLTgxMTQtMWI1MGI0ZGQ5MmU4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg', 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.'),
(85, 'The Kid', '1921', '68 min', 'Comedy, Drama, Family', 'Charles Chaplin', 'Carl Miller, Edna Purviance, Jackie Coogan, Charles Chaplin', 'English', '2 wins.', '8.3', 'https://m.media-amazon.com/images/M/MV5BZjhhMThhNDItNTY2MC00MmU1LTliNDEtNDdhZjdlNTY5ZDQ1XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg', 'The Tramp cares for an abandoned child, but events put that relationship in jeopardy.'),
(86, 'Singin\' in the Rain', '1952', '103 min', 'Comedy, Musical, Romance', 'Stanley Donen, Gene Kelly', 'Gene Kelly, Donald O\'Connor, Debbie Reynolds, Jean Hagen', 'English', 'Nominated for 2 Oscars. Another 5 wins & 7 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMWUyNjQ5MTAtNDJhYS00MWQ0LTk2ZTAtZmE4MWNlMjMwMzg3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'A silent film production company and cast make a difficult transition to sound.'),
(87, 'Scarface', '1983', '170 min', 'Crime, Drama', 'Brian De Palma', 'Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio', 'English, Spanish', 'Nominated for 3 Golden Globes. Another 4 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.'),
(88, 'Taxi Driver', '1976', '114 min', 'Crime, Drama', 'Martin Scorsese', 'Diahnne Abbott, Robinson Frank Adu, Victor Argo, Gino Ardito', 'English, Spanish', 'Nominated for 4 Oscars. Another 21 wins & 15 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.'),
(89, 'Lawrence of Arabia', '1962', '228 min', 'Adventure, Biography, Drama, History, War', 'David Lean', 'Peter O\'Toole, Alec Guinness, Anthony Quinn, Jack Hawkins', 'English, Arabic, Turkish', 'Won 7 Oscars. Another 23 wins & 14 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg', 'The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.'),
(90, 'Toy Story 3', '2010', '103 min', 'Animation, Adventure, Comedy, Family, Fantasy', 'Lee Unkrich', 'Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty', 'English, Spanish', 'Won 2 Oscars. Another 60 wins & 95 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it\'s up to Woody to convince the other toys that they weren\'t abandoned and to return home.'),
(91, 'The Sting', '1973', '129 min', 'Comedy, Crime, Drama', 'George Roy Hill', 'Paul Newman, Robert Redford, Robert Shaw, Charles Durning', 'English', 'Won 7 Oscars. Another 11 wins & 6 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNGU3NjQ4YTMtZGJjOS00YTQ3LThmNmItMTI5MDE2ODI3NzY3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg', 'Two grifters team up to pull off the ultimate con.'),
(92, 'Metropolis', '1927', '153 min', 'Drama, Sci-Fi', 'Fritz Lang', 'Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rogge, Fritz Rasp', 'German', '6 wins & 5 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMTg5YWIyMWUtZDY5My00Zjc1LTljOTctYmI0MWRmY2M2NmRkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'In a futuristic city sharply divided between the working class and the city planners, the son of the city\'s mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.'),
(93, 'Ikiru', '1952', '143 min', 'Drama', 'Akira Kurosawa', 'Takashi Shimura, Shin\'ichi Himori, Haruo Tanaka, Minoru Chiaki', 'Japanese', 'Nominated for 1 BAFTA Film Award. Another 5 wins & 1 nomination.', '8.3', 'https://m.media-amazon.com/images/M/MV5BZmM0NGY3Y2MtMTA1YS00YmQzLTk2YTctYWFhMDkzMDRjZWQzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg', 'A bureaucrat tries to find a meaning in his life after he discovers he has terminal cancer.'),
(94, 'Double Indemnity', '1944', '107 min', 'Crime, Drama, Film-Noir, Mystery, Thriller', 'Billy Wilder', 'Fred MacMurray, Barbara Stanwyck, Edward G. Robinson, Porter Hall', 'English', 'Nominated for 7 Oscars. Another 2 wins & 2 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BOTdlNjgyZGUtOTczYi00MDdhLTljZmMtYTEwZmRiOWFkYjRhXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg', 'An insurance representative lets himself be talked by a seductive housewife into a murder/insurance fraud scheme that arouses the suspicion of an insurance investigator.'),
(95, 'To Kill a Mockingbird', '1962', '129 min', 'Crime, Drama', 'Robert Mulligan', 'Gregory Peck, John Megna, Frank Overton, Rosemary Murphy', 'English', 'Won 3 Oscars. Another 10 wins & 16 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNmVmYzcwNzMtMWM1NS00MWIyLThlMDEtYzUwZDgzODE1NmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg', 'Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his children against prejudice.'),
(96, 'The Apartment', '1960', '125 min', 'Comedy, Drama, Romance', 'Billy Wilder', 'Jack Lemmon, Shirley MacLaine, Fred MacMurray, Ray Walston', 'English', 'Won 5 Oscars. Another 19 wins & 8 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BNzkwODFjNzItMmMwNi00MTU5LWE2MzktM2M4ZDczZGM1MmViXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg', 'A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.'),
(97, 'Indiana Jones and the Last Crusade', '1989', '127 min', 'Action, Adventure', 'Steven Spielberg', 'Harrison Ford, Sean Connery, Denholm Elliott, Alison Doody', 'English, German, Greek, Arabic', 'Won 1 Oscar. Another 7 wins & 22 nominations.', '8.2', 'https://m.media-amazon.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg', 'In 1938, after his father Professor Henry Jones, Sr. goes missing while pursuing the Holy Grail, Professor Henry \"Indiana\" Jones, Jr. finds himself up against Adolf Hitler\'s Nazis again to stop them from obtaining its powers.'),
(98, 'Incendies', '2010', '131 min', 'Drama, Mystery, War', 'Denis Villeneuve', 'Mustafa Kamel, Hussein Sami, Rémy Girard, Mélissa Désormeaux-Poulin', 'French, Arabic, English', 'Nominated for 1 Oscar. Another 39 wins & 15 nominations.', '8.3', 'https://m.media-amazon.com/images/M/MV5BMWE3MGYzZjktY2Q5Mi00Y2NiLWIyYWUtMmIyNzA3YmZlMGFhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg', 'Twins journey to the Middle East to discover their family history and fulfill their mother\'s last wishes.'),
(99, 'Up', '2009', '96 min', 'Animation, Adventure, Comedy, Family', 'Pete Docter, Bob Peterson(co-director)', 'Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson', 'English', 'Won 2 Oscars. Another 78 wins & 82 nominations.', '8.2', 'https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg', '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.'),
(100, 'L.A. Confidential', '1997', '138 min', 'Crime, Drama, Mystery, Thriller', 'Curtis Hanson', 'Kevin Spacey, Russell Crowe, Guy Pearce, James Cromwell', 'English', 'Won 2 Oscars. Another 89 wins & 84 nominations.', '8.2', 'https://m.media-amazon.com/images/M/MV5BMDQ2YzEyZGItYWRhOS00MjBmLTkzMDUtMTdjYzkyMmQxZTJlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg', 'As corruption grows in 1950s Los Angeles, three policemen -- one strait-laced, one brutal, and one sleazy -- investigate a series of murders with their own brand of justice.');

--
-- Indexuri pentru tabele eliminate
--

--
-- Indexuri pentru tabele `movies`
--
ALTER TABLE `movies`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pentru tabele eliminate
--

--
-- AUTO_INCREMENT pentru tabele `movies`
--
ALTER TABLE `movies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=208;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
